name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install poetry

    - name: Run tests
      run: |
        poetry run py.test -vv

