name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install tox

      - name: Run tests
        run: |
          tox

      - name: Test image
        run: |
          set -xe
          docker build . -t mirror-tool -f image/Containerfile
          docker run mirror-tool --help
