FROM registry.fedoraproject.org/fedora-minimal@sha256:7691f3e05234f426ec616f3d1876514e8a58379403fb1cae53e80b55dd28125c

RUN microdnf -y upgrade
RUN microdnf -y install python git-core /usr/bin/pip /usr/bin/poetry

ADD . /src

RUN mv /src/image/RH-IT-Root-CA.crt /etc/pki/ca-trust/source/anchors && update-ca-trust
ENV REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt

RUN cd /src && poetry install --no-dev -n

RUN ln -s /root/.cache/pypoetry/virtualenvs/mirror-tool*/bin/mirror-tool /usr/local/bin/mirror-tool
ENTRYPOINT ["/usr/local/bin/mirror-tool"]
