FROM registry.access.redhat.com/ubi8/ubi-minimal@sha256:e83a3146aa8d34dccfb99097aa79a3914327942337890aa6f73911996a80ebb8

RUN microdnf -y install python39 git-core

# FIXME: pin a poetry version?
RUN pip3 install poetry

ADD . /src

RUN mv /src/image/RH-IT-Root-CA.crt /etc/pki/ca-trust/source/anchors && update-ca-trust
ENV REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt

RUN cd /src && poetry install --no-dev -n

RUN ln -s /root/.cache/pypoetry/virtualenvs/mirror-tool*/bin/mirror-tool /usr/local/bin/mirror-tool
ENTRYPOINT ["/usr/local/bin/mirror-tool"]
