FROM registry.fedoraproject.org/fedora-minimal@sha256:82cbf7d47c03d991f1de18b4d981e43257d94a9d1fcec53236484d49129f106a

RUN microdnf -y upgrade
RUN microdnf -y install python git-core /usr/bin/pip

ADD . /src

RUN mv -v /src/image/*.crt /etc/pki/ca-trust/source/anchors && update-ca-trust
ENV REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt

RUN cd /src && pip install -rtest-requirements-3.11.txt && pip install .

ENTRYPOINT ["/usr/local/bin/mirror-tool"]
